kind: Deployment
apiVersion: apps/v1
metadata:
  name: veldeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: velpod
  template:
    metadata:
      name: velpod
      labels:
        name: velpod
    spec:
      containers:
        - name: vel-1
          image: prasadpawar2522/spring:1.0
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: velservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: velpod
  type: NodePort
